### ISSUE TITLE
Concise CSS and flexbox

### ISSUE THREAD

**Issue by aubreywullschleger** [IrinaKostevich/codecademy-tea-cozy#2]
Simplify!  Consider using group selectors for any repeated styles in your CSS like `display: flex;` and `flex-direction: column;` in location-card.css. 

Also, great job challenging yourself to use flexbox for the layout of your page!

**Comment by IrinaKostevich** [comment]
Regarding grouping of two properties inside of location-card.css - I think, it’s not a great idea, just because it will not bring much code reducing or even enlarging (i.e. with this group it has 2 more extra code lines), but it will bundle two components and will reduce code readability. I will take into account your consideration about grouping for future projects, where it will be applicable (with more common properties).
